# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0010_auto_20190320_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=127, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('view_password', models.CharField(default='', max_length=15)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now_add=True)),
                ('expire_day', models.IntegerField(default=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'permissions': (('view_hello', 'Can view hello word'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(default='', max_length=25, unique=True)),
                ('binary', models.BinaryField(max_length=4294967295)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OutputFileMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('md5', models.CharField(max_length=255, unique=True)),
                ('out_type', models.CharField(default='output', max_length=16)),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='文件创建日期')),
                ('ext', models.CharField(max_length=16, verbose_name='文件类型')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UploadFileMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=255)),
                ('md5', models.CharField(max_length=255, unique=True)),
                ('out_type', models.CharField(default='upload', max_length=16)),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='文件创建日期')),
                ('ext', models.CharField(max_length=16, verbose_name='文件类型')),
                ('user_id', models.IntegerField(verbose_name='上传文件的user_id')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
